name: pull-request-checks

on:
  pull_request:
    branches:
      - master

jobs:
  pull-request-checks:
    runs-on: [self-hosted, version-2.314.1]
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: install dependencies
        run: yarn install

      - name: set up environment
        run: echo "REACT_APP_BASE_URL=${{ secrets.REACT_APP_BASE_URL }}" >> $GITHUB_ENV

      - name: run lint
        run: yarn lint

      - name: run typescript compiler
        run: yarn tsc --noEmit

      - name: run tests
        run: yarn test
